### ISSUE TITLE
Adding architecture support for ARM

### ISSUE THREAD

**Issue by rperier** [GKernelCI/GBuildbot#52]
Hi,

Buildbot should support the most common popular architectures used in gentoo, these are amd64, arm and arm64. As a first step support for ARM architecture would be great:

- Create a dedicated builder for ARM (kernel 4.x as a first step, then gentoo_sources and other_sources)
- Cross build linux kernel for ARM (use an armv7a hardfloat toolchain)
- Test with qemu-system-arm for the vexpress a9 target (vexpress or versatile are usually the most tested and ready to use targets for ARM on qemu )

**Comment by rperier** [comment]
I have started to work on this already. It's mostly working.

**Comment by rperier** [comment]
I still need to fix a little thing with arm, then I will probably open MR tomorrow. See https://github.com/rperier/Gentoo_kernelCI

**Comment by aliceinwire** [comment]
buildbot still failing:
http://kernel1.amd64.dev.gentoo.org:8010/api/v2/logs/6520/raw

**Comment by kuzetsa** [comment]
while working on PR #63, "make defconfig" was how I did the .config

**Log:** [tested on arm](https://gist.github.com/kuzetsa/1688a88d186acf81714346c2178dffa6)

--syncconfig style .config generator attempts to update,
rather than making a new .config from upstream defaults.

I think switching to defconfig might fix these errors:

```
WARNING: unmet direct dependencies [...]
```

(*vanilla-sources, ck-sources, and gentoo-sources work on with defconfig*)

**Comment by aliceinwire** [comment]
support for arm as been implemented.
